In [10]:
import pandas as pd
df = []
def print_duty_cycles():
        i = 0
        while i <= 100:
            duty_small  = (i-0.0942)/0.0506
            duty_large = (i-0.132)/0.0709
            if duty_small > 100 or duty_large > 100:
                  break
            # print(f"Num:{i}, Duty Cycle Large: {duty_small}, Duty Cycle Small: {duty_large}")
            df.append([i,round(duty_large, 2),round(duty_small, 2)])
            i += 0.5
print_duty_cycles()
df = pd.DataFrame(df)
df.columns = ['Constant', 'Duty Cycle Small', 'Duty Cycle Large']

In [11]:
df

    Constant  Duty Cycle Small  Duty Cycle Large
0        0.0             -1.86             -1.86
1        0.5              5.19              8.02
2        1.0             12.24             17.90
3        1.5             19.29             27.78
4        2.0             26.35             37.66
5        2.5             33.40             47.55
6        3.0             40.45             57.43
7        3.5             47.50             67.31
8        4.0             54.56             77.19
9        4.5             61.61             87.07
10       5.0             68.66             96.95